### ISSUE TITLE
Custom KB Layout that worked in previous Pop doesn't work in COSMIC

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-settings#338]
> Not sure if this is a known issue or not. 
> 
> My custom layout that worked in X11/Wayland on stable PopOS! does not show up in the selector. It is english special layout. I installed it the same way as before (installation guide https://github.com/binarybottle/engram/tree/master/install/linux/x_keyboard_extension).
> 
> Maybe its not PopOS!'s issue, but it is a regression from previous version. 

 _Originally posted by @16hournaps in [#9](https://github.com/pop-os/cosmic-settings/issues/9#issuecomment-2094100813)_

**Comment by Drakulix** [comment]
`setxkbmap` can't work on wayland, however equivalent settings can be added to `~/.config/cosmic/com.system76.CosmicComp/v1/xkb_config`. Potentially we need to expose a way to add custom layouts in `cosmic-settings`?

**Comment by 16hournaps** [comment]
> `setxkbmap` can't work on wayland, however equivalent settings can be added to `~/.config/cosmic/com.system76.CosmicComp/v1/xkb_config`. Potentially we need to expose a way to add custom layouts in `cosmic-settings`?

I will try that and report if it worked or not. Previously there were no "add custom layout" option and that was fine because if you are willing to go out of your way to get a custom layout, learn it and then use it, you are already far far far from "normal user". The problem in this case was that since the system is new I could not just research it on the internet like I normaly do. But now if your solution works then this issue can serve as a reference for anyone who wants to do it.

**Comment by 16hournaps** [comment]
I verified your solution works :D Now I have engram on pop-os cosmic working again. You can close this, I will add a guide if I have time later here or on engrams github (or both).
