### ISSUE TITLE
Settings > Network & Wireless

### ISSUE THREAD

**Issue by maria-komarova** [pop-os/cosmic-settings#436]
The sub-category page providing entry to other network pages. 
![Network   Wireless](https://github.com/user-attachments/assets/8d604185-7013-445d-b244-b0a9de251451)
[Figma file](https://www.figma.com/design/Z6Z9Ox6WNkiiM8gcAkcElS/COSMIC-Settings-First-Release---Developer-Handoff?node-id=6921-84733&t=afTfg818R0XgQy4L-4).

**Comment by WatchMkr** [comment]
Leverage nm-connection-editor for adding and editing  connections. Examples:

`nm-connection-editor --type=802-3-ethernet -c` will show what the users sees when they choose to "Add network" in Wired

`nm-connection-editor --type=802-11-wireless -c` for wireless "Add network"

Bringing up the Edit page for a specific connection:
1. Capture wireless connection UUID from `nmcli connection`
2. Run [nm-connection-editor --edit=66e6c843-8a4d-4feb-a14f-b448bd1e2e4c](url) (replace with your UUID)

**Comment by jspurrier** [comment]
Ability to set VLANS would be quite useful in here as well especially for IT folk which a fair share of linux users probably are.

**Comment by SuperFredi** [comment]
The option to view/edit firewall settings or at least a link to the firewall implementation that is installed on the system. 
Also, if the firewall supports it, setting different firewall zones for specific connections/networks using the three-dot menu next to the connection/network.

An info page or modal for your current network / saved networks would also be nice, so that you can see your local IP-Address, MAC-Address, signal strength, speed, etc. (similar to android, if that makes sense). 

The ability to create a QR-Code for saved wireless networks could come in handy as well, if you want to connect a mobile device to the same network quickly.

**Comment by maria-komarova** [comment]
Thanks for the feedback, we'll look into it as we're working on the page. 


> An info page or modal for your current network / saved networks would also be nice, so that you can see your local IP-Address, MAC-Address, signal strength, speed, etc. (similar to android, if that makes sense).

This will definitely be possible to see. We are planning to use Network Manager for now to enable people to see the details and to edit it. It would be nicer to have it in COSMIC Settings itself but this will add much more implementation work and will move the release further away.

**Comment by Nyxiad** [comment]
I would love to see configurable default network settings which are applied to every network interface unless there are connection-specific settings. The main use case I have in mind is DNS; I want to set my default DNS servers on my laptop so that it's not picking up whatever the network's DHCP server is handing out. DNS-over-HTTPS and DNS-over-TLS support is a crucial feature for me.

**Comment by Eggroley** [comment]
> DNS-over-HTTPS and DNS-over-TLS support is a crucial feature for me.

Many DE's don't offer the ability to modify DoH or DoT through GUI. I would love to see this in Cosmic but I'm wondering if this is more a limitation of NetworkManager instead of the DE itself. Regardless though, this would be the first DE I've tried that has implemented this; so if it's possible, I'd love to see it added.

**Comment by bhh32** [comment]
I'd love to work on this. I have already been working on a project that's similar to this as a stand-in until the networking page is complete (https://github.com/bhh32/wifi). I could incorporate that work into the Wi-Fi page.

**Comment by mmstick** [comment]
@bhh32 We already worked on this. See https://github.com/pop-os/cosmic-settings/pull/531

**Comment by bhh32** [comment]
> @bhh32 We already worked on this. See https://github.com/pop-os/cosmic-settings/pull/531

Oh I didn't realize that you guys wanted to depend on gnome-network-manager still. My solution cuts gnome out and uses nmcli.

**Comment by mmstick** [comment]
We will eventually replace it when we have designs ready for the settings it provides.

**Comment by bhh32** [comment]
Are these not the designs,[432](https://github.com/pop-os/cosmic-settings/issues/432)?

**Comment by mmstick** [comment]
That's what the network settings PR implements.

**Comment by bhh32** [comment]
> That's what the network settings PR implements.

But with gnome-network-manager, right? I wouldn't mind doing the work to make it look like that without gnome tooling. Just trying to not have to have it retooled later since I've already been working a solution. If the design changes later it's something I don't mind doing. Would it be ok if I worked on putting something together and then have you guys look at it? If you don't like what I come up with that's ok too. I just want to contribute to making this the DE the best it can be and this is what I currently have to offer.

**Comment by bhh32** [comment]
Ok, I will wait for those designs, thank you.
