### ISSUE TITLE
[FEATURE] Support for TuneD 2.0 power settings

### ISSUE THREAD

**Issue by Hillard28** [pop-os/cosmic-settings#482]
[TuneD](https://github.com/redhat-performance/tuned) is a power profiles tool similar to power-profiles-daemon, which [will replace the latter starting with Fedora 41](https://fedoraproject.org/wiki/Changes/TunedAsTheDefaultPowerProfileManagementDaemon). At present, `tuned-ppd` is a translation API layer that translates the power-profiles-daemon API to TuneD. Gnome picks this up and if `tuned-ppd` is installed by running `sudo dnf swap power-profiles-daemon tuned-ppd` then the Gnome power settings work just as they did before. This is not the case for Cosmic, but it would seem (possibly ignorantly) that a fix may just require some additional checks?

**Comment by ryanabx** [comment]
The issue here is that TuneD currently does not offer itself on the new DBus interface that Power Profiles Daemon advertises itself on: `org.freedesktop.UPower.PowerProfiles`. It still uses the old interface, which I forget the exact name is something like `net.hadess.PowerProfiles`.

See this upstream PR: https://github.com/redhat-performance/tuned/pull/684


Question @WatchMkr , would it be helpful to have an `upstream` or `other-project` or similar tag that could be used when an issue is partially affected by another project?

**Comment by mmstick** [comment]
system76-power supports `net.hadess.PowerProfiles` and `org.freedesktop.UPower.PowerProfiles`, so that can be installed as a drop-in replacement. Not sure if it's worth supporting `net.hadess.PowerProfiles` here.

**Comment by Hillard28** [comment]
I'll probably just switch to system76-power then. I just figured it was worth calling out since I believe tuned is now the standard on fedora 41. That said, I know pop! is the priority here!

**Comment by ryanabx** [comment]
> I'll probably just switch to system76-power then. I just figured it was worth calling out since I believe tuned is now the standard on fedora 41. That said, I know pop! is the priority here!

No worries, we were just talking about it in the Fedora COSMIC sig group. I think tuned will end up supporting `org.freedesktop.UPower.PowerProfiles` before Fedora 41, so we will be all good. That said, upstream uses `system76-power` primarily, so nothing can go wrong from using what is supported in Pop!_OS

**Comment by Hillard28** [comment]
Looks like Fedora 41 has migrated to Tuned proper and power settings appear to be working! Guess this can be closed unless there's a reason to leave it open.
