### ISSUE TITLE
[FEATURE REQUEST] Focus follows cursor with 0 delay

### ISSUE THREAD

**Issue by BrodieRobertson** [pop-os/cosmic-settings#566]
On most tiling window managers if you hover over a window it is instantly given focus, currently COSMIC only switches focus with focus follows cursor after a few second delay.

A delay makes sense if you're coming from KDE, but the value should probably be configurable.

**Comment by git-f0x** [comment]
It seems the delay is currently 250ms. It would probably be relatively easy to add to Settings, though I'm also wondering if an option to only enable **Focus follows cursor** when tiling would be useful, since it can be quite disruptive when using floating windows.
Though it probably needs UX approval.

**Comment by BrodieRobertson** [comment]
I do like having focus follows cursors always enabled even with floating windows, I think the disruptiveness of it could be mitigated if you could grab focus without the window being put on top of the all of the others. I believe KDE Plasma has that as an option.

**Comment by joshuamegnauth54** [comment]
I opened a PR for the setting since it seems like the author of the feature wrote all of the necessary code in `cosmic-comp` already.

@BrodieRobertson You might want to open a new issue in `cosmic-comp` for the floating window suggestion though.
