### ISSUE TITLE
Input Devices panel first-round testing changes

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-settings#68]
- [x] Rename "Input" to "Input Devices"
- [x] Mouse > Remove Double-click speed
- [x] Mouse > Slowest Mouse speed is too slow when mouse acceleration is disabled. Start the bottom speed at 10% higher than its current speed.
- [x] Mouse > Scolling speed > remove first 10% and last 20%.
- [x] Touchpad > Touchpad Speed > Slowest speed is too slow when mouse acceleration is disabled and top too fast to be usable. Remove first 10% and last 10%.
- [x] Touchpad > remove double-click speed
- [x] Touchpad > add Disable while typing
- [x] Touchpad > Scrolling > Scolling speed > remove first 10% and last 20%
- [ ] Touchpad > Scrolling > Add Two-finger/Edge scolling radio buttons (new design)
- [ ] Touchpad > Add Click Behavior

**Comment by maria-komarova** [comment]
New design for the last checkbox:

![image](https://github.com/pop-os/cosmic-settings/assets/57502897/83000b44-66f1-4038-a979-d940a452b0d8)

**Comment by maria-komarova** [comment]
Design for clickpads that includes additional click behavior options:

![1100 - Nav - Touchpad - v2 - clickpad-tap-on](https://github.com/pop-os/cosmic-settings/assets/57502897/260cc457-06a4-4081-98e7-91e88a3a0f6b)

**Comment by loligans** [comment]
I don't know if this is already the case, but I would really appreciate separating Natural Scrolling between the Mouse and Touchpad. I like to configure my touchpad to use natural scrolling and my physical mouse to use not use natural scrolling.

**Comment by adrian5** [comment]
Apologies in advance if this isn't the right place to post this.

As a distant goal, consider an acceleration curve editor. Over the years I found the default acceleration behavior for mice to be a tradeoff between speed and precision. There already exists a superior alternative that combines fast swipes and pixel-accurate placement, it just has to be made accessible. Since my DE doesn't offer such control, I apply settings via script on startup:
```bash
xinput set-prop "$DEVICE" "libinput Accel Profile Enabled" 0 0 1 || exit
xinput set-prop "$DEVICE" "libinput Accel Custom Motion Step" 4
xinput set-prop "$DEVICE" "libinput Accel Custom Motion Points" 0.0 0.6 2.0 3.0
```
I suspect ideal parameters would differ between devices, so a dropdown with presets may not suffice.
