### ISSUE TITLE
Gaps can't get below 3 in the Cosmic settings

### ISSUE THREAD

**Issue by VasilisManol** [pop-os/cosmic-settings#805]
In Cosmic Settings it is impossible to set the "Gaps around tiled windows" to below 3 no matter the value of the "Active window hint size". It is possible to set them in the config file but not from the UI.

**Comment by bhh32** [comment]
I'll take a look at this this evening.

**Comment by bhh32** [comment]
> In Cosmic Settings it is impossible to set the "Gaps around tiled windows" to below 3 no matter the value of the "Active window hint size". It is possible to set them in the config file but not from the UI.

Please check the PR for this to make sure that it's the expected behavior.

**Comment by bhh32** [comment]
PR has been merged. Please close this issue.

**Comment by zupanibla** [comment]
If you are struggling with this issue in 2026 as I was. The fix for me was to first lower the "Active window hint size" to 0. You apparently have to do this even if you have the hints disabled.

<img width="862" height="161" alt="Image" src="https://github.com/user-attachments/assets/4554a2ea-f199-4795-9ca2-9233eccf841d" />

**Comment by bhh32** [comment]
I set it this way originally during a bug fix because otherwise the active hint will be bigger than the gap size and it bleeds over into the other windows. The bug was just this, the active hint could go bigger than the gap and overtook other windows.
